### 0. Generate auth token
GET http://admin:admin@172.20.213.209:8111/authenticationTest.html?csrf
Accept: application/json

### 1. Create newProjectDescription
POST http://172.20.213.209:8111/app/rest/projects
Content-Type: application/json
X-TC-CSRF-Token: b685a62b-5ef0-4509-8f45-fd0d4bb4b0af
Accept: application/json

{
  "parentProject": {
    "locator": "_ROOT"
  },
  "name": "name",
  "id": "id",
  "copyAllAssociatedSettings": true
}

### 2. Create build configuration
POST http://172.20.213.209:8111/app/rest/buildTypes
Content-Type: application/json
X-TC-CSRF-Token: 88827536-712d-4f80-89ff-6cd0e1abfa0a
Accept: application/json

{
  "id": "id",
  "name": "Print hello world",
  "newProjectDescription": {
    "id": "id"
  },
  "steps": {
    "step": [
      {
        "name": "Print hello world",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}

### 3. Run build
POST http://172.20.213.209:8111/app/rest/buildQueue
Content-Type: application/json
X-TC-CSRF-Token: 88827536-712d-4f80-89ff-6cd0e1abfa0a
Accept: application/json

{
  "buildType": {
    "id": "id"
  }
}

### 3. Check build status
GET http://172.20.213.209:8111/app/rest/builds/id:5
Content-Type: application/json
X-TC-CSRF-Token: 9d2ee98b-5ee8-4b5f-8b2d-05c38a0b0c06
Accept: application/json
